- type: entity
  name: flash
  parent: Flash
  suffix: recharging
  id: RechargeFlash # The Flash Revs are given at the start of the game.
  components:
    - type: LimitedCharges
      maxCharges: 3
      charges: 3
    - type: AutoRecharge
      rechargeDuration: 180
